### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mchalupa** [mchalupa/dg#15]
Just metabug for taking notes
- [ ] add tests
    - [x] for heap memory handling
    - [ ] for recursive programs
    - [x] try e. g. list or similar dynamic ADT
    - [ ] floats? it should be working, but check
    - [ ] points-to, def-use and reaching defs analysis
    - [ ] post-dominance frontiers and control dependencies
- [ ] implement better slicing
    - [ ] implement summary edges
    - [ ] implement NodesWalk via summary edges
    - [x] slice first BBs away and then slice away instructions from the rest of BBs
          so that we'll keep the projection to llvm consistent
- [x] control dependencies
    - [x] infinite loops are broken
    - [ ] implement better algorithm (that handles inifinite loops)

- [ ] handle instructions
    - [x] varargs
    - [x] phi nodes
    - [x] switch (not handled but looks working)
    - [ ] indirectbr
    - [x ] inlined assembler
        - [ ] either just give up with inlined assembler or go through it, gather the
              top-level variables that can be modified in it (if it is possible) and
              mark them as modified, so it'll be unprecise but sound
    - [x] inttoptr, ptrtoint
        - [x] workaround it by always setting to unknown location for now
        - [ ] make it working properly!
    - [ ]  cmpxchg (modifies memory)
    - [ ] atomicrmw (modifies memory)
    - [ ] exctractvalue (aggregate type - like struct, array etc.)
          similar to GEP
    - (exctractelement) vectors
    - (invoke, resume, catchpad) WTH?

- [x] handle dynamic allocation (malloc, calloc, etc.)
    - [ ] has malloc without store a definition? It's like alloca, hadle we like alloca?
    - [ ] handle realloc
- [ ] handle carefully unknown offsets in pointers #20 and reaching defs
- [ ] refactor old ugly code

------------------------------------------------------------------------
- [x] fix handling undefined functions #40 
- [x] handle function pointers #19
     - [x] handle constant global function pointers
     - [x] handle intrinsic functions initializers
- [x] handle intrinsic functions
    we handle them as undefined functions, which should be correct,
    but not so precise (e. g. memcpy marks both pointers as modified,
    but actually it modifies only one)

- [x] handle null pointers
- [x] handle constant expressions
- [x] full support for globals
- [x] interprocedural slicing

**Comment by mchalupa** [comment]
This was for 0.0.2, closing since most of these are obsolete. The ones that are not obsolete are filed as separate bugs
